-- CREATE TABLE #EXPLRE (
--     TIND INT IDENTITY(1,1) PRIMARY KEY,
--     TKEY INT,
--     TF NVARCHAR(100)
-- );
-- 
-- INSERT INTO #EXPLRE (TKEY, TF)
-- SELECT ABS(CHECKSUM(NEWID())) % 30000, N'строка'
-- FROM master.dbo.spt_values WHERE type = 'P' AND number < 1000;

-- Удаляем старый и создаем с FILLFACTOR
-- DROP INDEX IX_EXPLRE_TKEY ON #EXPLRE;
--CREATE INDEX IX_EXPLRE_TKEY ON #EXPLRE(TKEY) WITH (FILLFACTOR = 65);




--CHECKPOINT;
--DBCC DROPCLEANBUFFERS;
--SELECT * FROM #EXPLRE WHERE TKEY BETWEEN 5000 AND 7000;


SELECT DB_NAME() as CurrentDatabase;