ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

DROP TABLE T_LIST_STG CASCADE CONSTRAINTS;
DROP TABLE T_LIST     CASCADE CONSTRAINTS;
DROP TABLE T_HASH     CASCADE CONSTRAINTS;
DROP TABLE T_INTERVAL CASCADE CONSTRAINTS;
DROP TABLE T_RANGE    CASCADE CONSTRAINTS;

-- 1. T_RANGE – диапазонное секционирование (NUMBER)
CREATE TABLE T_RANGE (
    ID        NUMBER       NOT NULL,
    DATA      VARCHAR2(100),
    CONSTRAINT T_RANGE_PK PRIMARY KEY (ID)
)
PARTITION BY RANGE (ID)
(
    PARTITION P_R_1   VALUES LESS THAN (100),
    PARTITION P_R_2   VALUES LESS THAN (200),
    PARTITION P_R_3   VALUES LESS THAN (MAXVALUE)
);


-- 2. T_INTERVAL – интервальное секционирование (DATE)
CREATE TABLE T_INTERVAL (
    ID        NUMBER       NOT NULL,
    CREATED   DATE         NOT NULL,
    DATA      VARCHAR2(100),
    CONSTRAINT T_INTERVAL_PK PRIMARY KEY (ID, CREATED)
)
PARTITION BY RANGE (CREATED)
INTERVAL ( NUMTOYMINTERVAL(1, 'MONTH') )  -- шаг 1 месяц
(
    PARTITION P_INT_START VALUES LESS THAN (DATE '2024-01-01')
);


-- 3. T_HASH – хэш-секционирование (VARCHAR2)
CREATE TABLE T_HASH (
    CODE      VARCHAR2(20) NOT NULL,
    DATA      VARCHAR2(100),
    CONSTRAINT T_HASH_PK PRIMARY KEY (CODE)
)
PARTITION BY HASH (CODE)
PARTITIONS 3;


-- 4. T_LIST – списочное секционирование (CHAR)
CREATE TABLE T_LIST (
    REGION    CHAR(2)      NOT NULL,
    DATA      VARCHAR2(100),
    CONSTRAINT T_LIST_PK PRIMARY KEY (REGION, DATA)
)
PARTITION BY LIST (REGION)
(
    PARTITION P_L_EU     VALUES ('EU'),
    PARTITION P_L_US     VALUES ('US'),
    PARTITION P_L_AS     VALUES ('AS'),
    PARTITION P_L_OTHERS VALUES (DEFAULT)
);


-- 5. INSERT в T_RANGE, T_INTERVAL, T_HASH, T_LIST
--    Данные должны попасть во все секции

-- 5.1 RANGE
INSERT INTO T_RANGE VALUES ( 10, 'RANGE < 100');
INSERT INTO T_RANGE VALUES ( 50, 'RANGE < 100');
INSERT INTO T_RANGE VALUES (150, 'RANGE 100-199');
INSERT INTO T_RANGE VALUES (180, 'RANGE 100-199');
INSERT INTO T_RANGE VALUES (250, 'RANGE >= 200');
INSERT INTO T_RANGE VALUES (350, 'RANGE >= 200');

-- Показать, какие партиции есть и их границы
SELECT PARTITION_NAME, HIGH_VALUE
FROM   USER_TAB_PARTITIONS
WHERE  TABLE_NAME = 'T_RANGE'
ORDER BY PARTITION_POSITION;


-- 5.2 INTERVAL
INSERT INTO T_INTERVAL VALUES (1, DATE '2023-12-15', 'before 2024');   -- P_INT_START
INSERT INTO T_INTERVAL VALUES (2, DATE '2024-01-10', 'jan 2024');      -- авто-секция
INSERT INTO T_INTERVAL VALUES (3, DATE '2024-02-05', 'feb 2024');      -- авто-секция
INSERT INTO T_INTERVAL VALUES (4, DATE '2024-03-20', 'mar 2024');      -- авто-секция

-- Посмотреть, какие секции появились
SELECT PARTITION_NAME, HIGH_VALUE
FROM   USER_TAB_PARTITIONS
WHERE  TABLE_NAME = 'T_INTERVAL'
ORDER BY PARTITION_POSITION;


-- 5.3 HASH
INSERT INTO T_HASH VALUES ('A001', 'hash a');
INSERT INTO T_HASH VALUES ('B001', 'hash b');
INSERT INTO T_HASH VALUES ('C001', 'hash c');
INSERT INTO T_HASH VALUES ('D001', 'hash d');
INSERT INTO T_HASH VALUES ('E001', 'hash e');
INSERT INTO T_HASH VALUES ('F001', 'hash f');

-- Покажем распределение по партициям через статистику
SELECT PARTITION_NAME, NUM_ROWS
FROM   USER_TAB_PARTITIONS
WHERE  TABLE_NAME = 'T_HASH'
ORDER BY PARTITION_POSITION;


-- 5.4 LIST
INSERT INTO T_LIST VALUES ('EU', 'row eu 1');
INSERT INTO T_LIST VALUES ('US', 'row us 1');
INSERT INTO T_LIST VALUES ('AS', 'row as 1');
INSERT INTO T_LIST VALUES ('EU', 'row eu 2');
INSERT INTO T_LIST VALUES ('RU', 'row other ru');   -- попадёт в P_L_OTHERS
INSERT INTO T_LIST VALUES ('BR', 'row other br');   -- тоже в P_L_OTHERS

COMMIT;

-- Показать, что данные реально во всех секциях
SELECT REGION, DATA, 'P_L_EU'     AS PART
FROM   T_LIST PARTITION (P_L_EU)
UNION ALL
SELECT REGION, DATA, 'P_L_US'
FROM   T_LIST PARTITION (P_L_US)
UNION ALL
SELECT REGION, DATA, 'P_L_AS'
FROM   T_LIST PARTITION (P_L_AS)
UNION ALL
SELECT REGION, DATA, 'P_L_OTHERS'
FROM   T_LIST PARTITION (P_L_OTHERS);


-- 6. Перемещение строк между секциями при UPDATE ключа
-- 6.1 RANGE: ID из P_R_1 -> P_R_2
UPDATE T_RANGE
SET ID = 120
WHERE ID = 10;

-- проверка
SELECT ID, DATA FROM T_RANGE PARTITION (P_R_1);
SELECT ID, DATA FROM T_RANGE PARTITION (P_R_2);

-- 6.2 LIST: REGION из P_L_EU -> P_L_US
UPDATE T_LIST
SET REGION = 'US'
WHERE REGION = 'EU'
  AND DATA = 'row eu 1';

-- проверка
SELECT REGION, DATA FROM T_LIST PARTITION (P_L_EU);
SELECT REGION, DATA FROM T_LIST PARTITION (P_L_US);

COMMIT;


-- 7. ALTER TABLE ... MERGE для одной таблицы (T_RANGE)
ALTER TABLE T_RANGE
MERGE PARTITIONS P_R_1, P_R_2
INTO PARTITION P_R_12;

SELECT PARTITION_NAME, HIGH_VALUE
FROM   USER_TAB_PARTITIONS
WHERE  TABLE_NAME = 'T_RANGE'
ORDER BY PARTITION_POSITION;


-- 8. ALTER TABLE ... SPLIT для одной таблицы (T_RANGE)
--    делим P_R_3 на две по границе 300
ALTER TABLE T_RANGE
SPLIT PARTITION P_R_3
AT (300)
INTO (
    PARTITION P_R_3_LOW,
    PARTITION P_R_3_HIGH
);

SELECT PARTITION_NAME, HIGH_VALUE
FROM   USER_TAB_PARTITIONS
WHERE  TABLE_NAME = 'T_RANGE'
ORDER BY PARTITION_POSITION;


-- 9. ALTER TABLE ... EXCHANGE для одной таблицы (T_LIST)
CREATE TABLE T_LIST_STG (
    REGION    CHAR(2)      NOT NULL,
    DATA      VARCHAR2(100),
    CONSTRAINT T_LIST_STG_PK PRIMARY KEY (REGION, DATA)
);

INSERT INTO T_LIST_STG VALUES ('EU', 'stg eu 1');
INSERT INTO T_LIST_STG VALUES ('EU', 'stg eu 2');
COMMIT;

ALTER TABLE T_LIST
EXCHANGE PARTITION P_L_EU
WITH TABLE T_LIST_STG
WITHOUT VALIDATION;

-- проверка: что теперь в P_L_EU и в T_LIST_STG
SELECT REGION, DATA, 'P_L_EU' AS SRC
FROM   T_LIST PARTITION (P_L_EU);

SELECT REGION, DATA, 'T_LIST_STG' AS SRC
FROM   T_LIST_STG;


-- 10. SELECT-запросы по метаданным и секциям
-- 10.1 Список всех секционированных таблиц в текущей схеме
SELECT TABLE_NAME
FROM   USER_PART_TABLES
ORDER BY TABLE_NAME;

-- 10.2 Список всех секций таблицы T_RANGE (можно подставить любую)
SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, PARTITION_POSITION
FROM   USER_TAB_PARTITIONS
WHERE  TABLE_NAME = 'T_RANGE'
ORDER BY PARTITION_POSITION;

-- 10.3 Все значения из секции по имени секции (пример: P_L_OTHERS T_LIST)
SELECT *
FROM   T_LIST PARTITION (P_L_OTHERS);

-- 10.4 Все значения из секции "по ссылке" (по ключу, через PARTITION FOR)
--     здесь Oracle сам определит нужную партицию по ключу 'US'
SELECT *
FROM   T_LIST PARTITION FOR ('US');






